#!/usr/bin/env python3
"""Round-2 assayer/scorer: back-stamp cross-ledger refs and append f-093..f-125."""
import json, pathlib

ROOT = pathlib.Path("/Users/sma/projects/Sylveste/docs/research/flux-melange/clavain-core-verse-improvements")
LEDGER = ROOT / "heat-ledger.jsonl"

# --- back-references onto existing findings (convergence both directions) ---
BACK_CONV = {
    "f-084": ["f-093", "f-094", "f-095", "f-096", "f-097", "f-099", "f-100"],
    "f-085": ["f-093"],
    "f-052": ["f-093", "f-098"],
    "f-014": ["f-096"],
    "f-053": ["f-096"],
    "f-029": ["f-094", "f-098"],
    "f-054": ["f-098"],
    "f-051": ["f-094"],
    "f-009": ["f-095"],
    "f-023": ["f-101"],
    "f-075": ["f-101", "f-102", "f-103", "f-104", "f-105", "f-106", "f-108"],
    "f-043": ["f-102"],
    "f-080": ["f-102"],
    "f-082": ["f-102", "f-108"],
    "f-079": ["f-103"],
    "f-048": ["f-103", "f-106"],
    "f-081": ["f-105"],
    "f-044": ["f-107"],
    "f-018": ["f-109", "f-110", "f-111", "f-113", "f-116", "f-119"],
    "f-071": ["f-109", "f-111", "f-116"],
    "f-072": ["f-112", "f-117"],
    "f-073": ["f-110", "f-114", "f-119"],
    "f-045": ["f-115"],
    "f-039": ["f-119"],
    "f-040": ["f-119"],
    "f-001": ["f-120", "f-125"],
    "f-025": ["f-120"],
    "f-078": ["f-120", "f-125"],
    "f-086": ["f-121"],
    "f-002": ["f-121"],
    "f-007": ["f-122"],
    "f-008": ["f-122"],
    "f-089": ["f-122", "f-124"],
    "f-003": ["f-123"],
    "f-092": ["f-123"],
    "f-033": ["f-124"],
    "f-087": ["f-125"],
}
BACK_DIS = {"f-008": ["f-122"]}

PD = {"kind": "lens", "agents": ["fd-provenance-drift"],
      "parent_lenses": ["fd-lifecycle-drift", "fd-scriptorium-transmission"],
      "source_domains": ["release engineering", "manuscript stemmatics"]}
KC = {"kind": "lens", "agents": ["fd-kernel-contract"], "parent_lenses": [],
      "source_domains": ["kernel/API boundary engineering"]}
CS = {"kind": "fusion", "agents": ["fd-canonization-safety"],
      "parent_lenses": ["fd-kernel-contract", "fd-ecosystem-consolidation"],
      "source_domains": ["kernel/API boundary engineering", "platform-consolidation architecture"]}


def f(fid, src, claim, loc, sev, ev, nov, br, lk, taste, tk, clu, conv, dis, ij, status):
    return {"id": fid, "round": 2, "source": src, "claim": claim, "location": loc,
            "severity": sev, "evidence": ev, "novelty": nov,
            "risk": {"blast_radius": br, "likelihood": lk, "product": br * lk},
            "taste": taste, "taste_kind": tk, "cluster_id": clu,
            "convergence_refs": conv, "disagreement_refs": dis,
            "intersection_justification": ij, "status": status}


NEW = [
    # ---- probe-0: DEEPEN f-084 exemplar (fd-provenance-drift) ----
    f("f-093", PD,
      "codex-auto-refresh.sh defaults CLAVAIN_DIR/CLAVAIN_REPO_URL to the GitHub clone, ff-pulls it, then executes the fleet installer FROM that clone; override knobs (CLAVAIN_DIR, CLAVAIN_REPO_URL, --source, --clone-root) all exist but no script, scheduler, or doc ever sets them to the Sylveste tree — the distribution fallback silently operates as the standing exemplar (V5: knobs-unused upheld).",
      "os/Clavain/scripts/codex-auto-refresh.sh:18-19,46-52,76", "P2",
      "defaults at :18-19; git pull --ff-only at :76; installer invoked from clone at :46-47,:51-52; no setter of the overrides found anywhere",
      1, 2, 2, 0, None, "installer-self-transmission", ["f-085", "f-052", "f-084"], [], None, "upheld"),
    f("f-094", PD,
      "plugin_repo_url() hardcodes https://github.com/mistakeknot/%s.git and ensure_repo() clones/ff-pulls every companion from GitHub; there is NO code path that prefers the local Sylveste/interverse/<plugin> checkouts (71 present, each a live git repo) — the canonical tree is invisible to the installer (direct re-confirmation of f-084 core).",
      "os/Clavain/scripts/install-codex-interverse.sh:322-324,898-915", "P2",
      "hardcoded template at :322-324; ensure_repo at :898-915; 71 nested plugin checkouts on disk",
      0, 3, 3, 0, None, "exemplar-misdeclaration-github", ["f-084", "f-051", "f-029"], [], None, "upheld"),
    f("f-095", PD,
      "The Codex-only install path carries the same GitHub-default exemplar: REPO_URL_DEFAULT=https://github.com/mistakeknot/Clavain.git — the pattern extends beyond the companion installer f-084 named.",
      "os/Clavain/scripts/install-codex.sh:16 (also :25, clone at :176)", "P2",
      "REPO_URL_DEFAULT constant at :16",
      1, 2, 3, 0, None, "exemplar-misdeclaration-github", ["f-084", "f-009"], [], None, "upheld"),
    f("f-096", PD,
      "Every drift check compares a repo against its own GitHub origin (repo_remote_diff_status resolves @{upstream} via git ls-remote origin); no check anywhere answers 'is the installed snapshot behind the Sylveste tree on THIS machine' — light mode inspects only Sylveste + ~/.codex/clavain, full mode adds companions but still vs GitHub.",
      "os/Clavain/scripts/check-install-updates.sh:150-158,273-319", "P2",
      "ls-remote origin at :150-158; light-mode scope :273-319; full-mode :307-318",
      1, 2, 3, 0, None, "drift-detection-coverage-gap", ["f-014", "f-053", "f-084"], [], None, "upheld"),
    f("f-097", PD,
      "install.sh is the exception that adjudicates intent: find_local_clavain_source() prefers the local checkout and GitHub clones are curl-pipe fallbacks only — GitHub-as-exemplar is INTENTIONAL as a distribution channel for machines without the tree, ACCIDENTAL as the standing default on machines that have it.",
      "install.sh:95,505,595,655,700", "P3",
      "find_local_clavain_source at :95 used at :581; clone fallbacks at :505,:595,:655,:700",
      2, 1, 2, 0, None, "exemplar-misdeclaration-github", ["f-084"], [], None, "upheld"),
    f("f-098", PD,
      "zklw (first probe) replicates the snapshot-routing pattern — 46 ~/.agents/skills links resolve to ~/.codex/<plugin> snapshots (interlock stale since 2026-07-04) — with a wrinkle: ~/.codex/clavain does not exist and the clavain skill points to a standalone ~/projects/Clavain GitHub clone, a THIRD undeclared Clavain lineage alongside Sylveste/os/Clavain and ~/.codex/clavain; no crontab/systemd timer runs codex-auto-refresh there either.",
      "zklw:~/.agents/skills -> ~/.codex/<plugin>; zklw:~/projects/Clavain", "P2",
      "46 links sampled; interlock snapshot last commit 2026-07-04; standalone clone at 2026-08-01; no scheduler registration",
      2, 2, 2, -1, "smell", "routing-split-brain", ["f-054", "f-029", "f-052"], [], None, "upheld"),
    f("f-099", PD,
      "Sylveste's own origin is GitHub on BOTH machines (Mac https, zklw ssh) at the same 2026-08-05 commit — for the Sylveste repo itself GitHub is the de-facto sync transport and 'zklw canonical' holds only socially; the doctrine contradiction is confined to the plugin-install layer, not Sylveste sync (scope-narrowing adjudication).",
      "git remotes, both machines", "P3",
      "both origins GitHub, same HEAD commit on both machines",
      2, 1, 2, 0, None, "exemplar-misdeclaration-github", ["f-084"], [], None, "upheld"),
    f("f-100", PD,
      "DESIGN (proposal, not defect): exemplar-routing fix shape — one SYLVESTE_EXEMPLAR_ROOT detection helper (consolidating discover_sylveste_root + find_local_clavain_source), routed through install-codex-interverse.sh::ensure_repo (fleet chokepoint), codex-auto-refresh.sh defaults, and check-install-updates.sh plus a new local canonical-vs-snapshot drift check needing no network; ~60-90 lines, 3 call sites; one remediation closes f-084/f-085/f-052 and the snapshot leg of f-029.",
      "os/Clavain/scripts/{install-codex-interverse.sh,codex-auto-refresh.sh,check-install-updates.sh} + new lib-exemplar.sh", "P2",
      "verdict.md fix sizing: helper + 3 call sites; detection logic already exists at check-install-updates.sh:100-117 and install.sh:95",
      2, 1, 1, 0, None, "exemplar-routing-fix", ["f-084", "f-085", "f-052"], [], None, "raw"),
    # ---- probe-1: DEEPEN gate-mode surface (fd-kernel-contract) ----
    f("f-101", KC,
      "emitInterspectEvent — the only audit emitter on the Go gate path — calls `ic events add`, a subcommand that does NOT exist (events.go:18 accepts only tail/cursor/emit/record/list-review/list-agency); rc=3 is discarded by `_, _ =`, so the calibration_skip_gate 'audit event' advertised at phase.go:343-348 has never landed anywhere (V1: events-add-void upheld). Working vehicle is `ic events record --source=interspect`.",
      "os/Clavain/cmd/clavain-cli/gate_calibration.go:186-189 + phase.go:341-350", "P1",
      "runIC(\"events\",\"add\",...) at gate_calibration.go:188; events.go:18 subcommand list; `_, _ =` discard",
      3, 2, 3, 0, None, "gate-audit-emitter-dead", ["f-023", "f-075"], [], None, "upheld"),
    f("f-102", KC,
      "Exhaustive inventory of the gate-mode weakening surface: 27 weakening-resolution sites (30 call sites counting the four budget.New(nil) wirings), 23 leave ZERO durable trace when they weaken; the only 4 traced sites are interphase lib-gates.sh writing ad-hoc telemetry.jsonl/bd notes, not the kernel event spine — no single query answers 'when did any gate weaken, anywhere?'.",
      "os/Clavain/cmd/clavain-cli/{phase,handoff,satisfaction,gate_calibration}.go + hooks/lib-sprint.sh + core/intercore + interverse/interphase/hooks/lib-gates.sh", "P1",
      "probe-1 findings-index tally: 27 sites, 23 NO-TRACE, 4 traced (all interphase); site-by-site table in verdict.md",
      2, 3, 2, 0, None, "gate-mode-self-weakening", ["f-075", "f-043", "f-080", "f-082"], [], None, "upheld"),
    f("f-103", KC,
      "Bash defaults ENFORCE on missing spec (lib-sprint.sh:1089 `|| gate_mode=\"enforce\"`) while Go getGateMode/getGateModeForPhase default SHADOW on spec-load error AND on missing key (handoff.go:693-724; phase.go:360,383) — same absent file, opposite enforcement postures, re-verified this round (f-048/f-079 core mechanism).",
      "os/Clavain/hooks/lib-sprint.sh:1089 vs cmd/clavain-cli/handoff.go:693-724, phase.go:360,383", "P2",
      "bash `|| gate_mode=\"enforce\"` vs Go hardcoded \"shadow\" fallbacks at handoff.go:696,701,723",
      0, 2, 2, 0, None, "bash-go-semantics-split", ["f-079", "f-075", "f-048"], [], None, "upheld"),
    f("f-104", KC,
      "The CLAVAIN_SKIP_GATE block message advertises '(audited)' but no audit record is written on either path — a user-facing audit overclaim printed exactly when the gate is being bypassed.",
      "os/Clavain/hooks/lib-sprint.sh:1115-1119", "P3",
      "block message at :1119 contains '(audited)'; no event/log write on either branch",
      2, 1, 2, -1, "smell", "gate-mode-self-weakening", ["f-075"], [], None, "upheld"),
    f("f-105", KC,
      "CLAVAIN_DISABLE_GATES=true in interphase kills ALL gate enforcement with one env var; the lever does not exist in clavain-cli or lib-sprint.sh, so the bypass surface differs by which enforce_gate implementation runs; trace is a best-effort `|| true` append to ~/.clavain/telemetry.jsonl.",
      "interverse/interphase/hooks/lib-gates.sh:354-358", "P2",
      "env check at :354-358; absent from phase.go/lib-sprint.sh; telemetry append with || true",
      2, 2, 2, 0, None, "gate-mode-self-weakening", ["f-075", "f-081"], [], None, "upheld"),
    f("f-106", KC,
      "Complete env-var weakening lever set enumerated fleet-wide: CLAVAIN_SKIP_GATE (3 implementations), CLAVAIN_SKIP_HANDOFF, CLAVAIN_SKIP_BUDGET (x2), CLAVAIN_SKIP_CANARY, CLAVAIN_ALLOW_UNSAFE, CLAVAIN_DISABLE_GATES, and inverted CLAVAIN_GATE_FAIL_CLOSED — 4 of 7 previously unledg ered; none emits a durable event before returning.",
      "phase.go:341,353,141; lib-sprint.sh:1115,1314; lib-gates.sh:137,354; skills/landing-a-change/SKILL.md:85; scripts/dispatch.sh:427", "P2",
      "probe-1 env-var section lists all 7 with call sites",
      2, 2, 2, 0, None, "gate-mode-self-weakening", ["f-075", "f-048"], [], None, "upheld"),
    f("f-107", KC,
      "complexity.mode defaults 'off' and has no behavioral consumer outside config tests — a defined-but-inert lever that reads like a routing safety floor and isn't one.",
      "core/intercore/internal/routing/config.go:111-113", "P3",
      "default off at :111-113; no consumer found outside config tests",
      2, 1, 1, 0, None, "inert-config-lever", ["f-044"], [], None, "upheld"),
    f("f-108", KC,
      "DESIGN (proposal, not defect): gate failure-direction policy draft ('a weakening that leaves no trace is a bug, regardless of direction'; enforce-by-default, fail-closed for design/ship, shadow as explicit opt-in that always emits gate_mode_resolved) plus 3-file minimal fix — handoff.go enforce-default + resolveGateMode audit wrapper + gate_calibration.go events-add->record one-liner; lib-sprint.sh emit on off/shadow/skip paths; contracts/gate-failure-direction.md.",
      "os/Clavain/cmd/clavain-cli/handoff.go + hooks/lib-sprint.sh + core/intercore/contracts/gate-failure-direction.md", "P2",
      "verdict.md policy paragraph + minimal fix shape; defers budget-recorder wiring, f-042 alignment, PreToolUse Bash matcher",
      2, 1, 1, 0, None, "gate-failure-direction-policy", ["f-082", "f-075", "f-101"], [], None, "raw"),
    # ---- probe-2: DEEPEN event contract (fd-kernel-contract) ----
    f("f-109", KC,
      "Cursor is persisted per batch immediately after stdout encode, before the consumer processes; the sole production consumer (interspect) crashing between `ic events tail` exit and _interspect_insert_evidence silently drops the whole batch — direct re-confirmation of f-018/f-071.",
      "core/intercore/cmd/ic/events.go:157-160 + interverse/interspect/hooks/lib-interspect.sh:2541-2575", "P1",
      "saveCursor at :157-160; crash window at lib-interspect.sh:2541-2575",
      0, 2, 2, 0, None, "event-delivery-at-most-once", ["f-018", "f-071"], [], None, "upheld"),
    f("f-110", KC,
      "The correct contract is ALREADY WRITTEN in intercore-vision.md:336-349 — read-only tail, explicit `ic events cursor set` after processing, durable vs ephemeral cursors, prune with durable-cursor protection, stable per-source ids — and never implemented (cursor subcommands are list/reset/register only; tail auto-advances; prune absent; TTL 24h not 7d). The fix is converge-code-to-vision; no new design needed (V4: contract-written-not-implemented upheld).",
      "core/intercore/docs/product/intercore-vision.md:336-349 vs cmd/ic/events.go:18,157-160,182-192", "P1",
      "vision contract text at :336-349; events.go subcommand list lacks cursor set and prune",
      2, 2, 2, 0, None, "event-delivery-at-most-once", ["f-018", "f-071", "f-073"], [], None, "upheld"),
    f("f-111", KC,
      "Silent per-event loss WITHOUT any crash: the consumer loop tolerates per-event insert failures with `|| true` and skips jq-unparseable lines, but the cursor for those events was already advanced by the tail process — consumer error-tolerance becomes permanent data loss.",
      "interverse/interspect/hooks/lib-interspect.sh:2548-2556,2574 + core/intercore/cmd/ic/events.go:158", "P1",
      "|| true at :2574; jq skip at :2548-2556; cursor saved at events.go:158 before loop runs",
      2, 2, 2, 0, None, "event-delivery-at-most-once", ["f-018", "f-071"], [], None, "upheld"),
    f("f-112", KC,
      "Ephemeral cursor TTL is 24h in code but 7 days in the vision doc; neither value appears in contracts/events/README.md; expiry silently resets the consumer to 0,0,0,0,0 via the loadCursor error path, replaying from event zero on next poll.",
      "core/intercore/cmd/ic/events.go:268,717-731,753 vs docs/product/intercore-vision.md:343", "P2",
      "24h constant vs 7d doc text; reset-to-zero at :717-731",
      1, 1, 2, 0, None, "event-delivery-at-most-once", ["f-072"], [], None, "upheld"),
    f("f-113", KC,
      "Mixing manual --since-* replay flags with --consumer does not load the cursor but STILL saves it — a manual historical replay silently rewrites the consumer's high-water mark; no guard exists.",
      "core/intercore/cmd/ic/events.go:115-117,158", "P2",
      "cursor load skipped at :115-117 while save at :158 runs unconditionally",
      3, 2, 2, 0, None, "event-delivery-at-most-once", ["f-018"], [], None, "upheld"),
    f("f-114", KC,
      "Vision promises `ic events prune --older-than` with the guarantee that no event is pruned ahead of any durable consumer's cursor; no prune subcommand exists — durable registration currently buys no protection and event tables grow unbounded (direct f-073 restatement).",
      "core/intercore/docs/product/intercore-vision.md:345 vs cmd/ic/events.go subcommand list", "P2",
      "events.go subcommands: tail/cursor/emit/record/list-review/list-agency only",
      0, 1, 2, 0, None, "events-prune-guarantee-missing", ["f-073"], [], None, "upheld"),
    f("f-115", KC,
      "No global monotonic event sequence exists: the cursor is a composite 5-tuple over per-table AUTOINCREMENT ids; created_at is unixepoch seconds (tie-prone, unusable as cursor); contracts README documents sources but never the composite-cursor shape as API — consumers must infer the contract from the cursor JSON payload.",
      "core/intercore/cmd/ic/events.go + internal/event/store.go:106-244 + contracts/events/README.md", "P2",
      "5-tuple cursor shape; created_at second-resolution; README silent on cursor shape",
      2, 1, 2, 0, None, "event-cursor-shape-undocumented", ["f-045"], [], None, "upheld"),
    f("f-116", KC,
      "The sole consumer is NOT replay-safe: idx_evidence_source_event_id is a NON-UNIQUE index and _interspect_insert_evidence is a plain INSERT — switching to at-least-once (replay-capable) delivery today would duplicate evidence rows on every replay (V4: interspect non-replay-safe upheld). Fix is small: unique partial index on (source_event_id, source_table) + INSERT OR IGNORE.",
      "interverse/interspect/hooks/lib-interspect.sh:111,206,3090", "P2",
      "non-unique index at :206; plain INSERT at :3090",
      3, 2, 2, 0, None, "interspect-replay-not-idempotent", ["f-018", "f-071"], [], None, "upheld"),
    f("f-117", KC,
      "loadCursor swallows 'cursor missing' and 'cursor JSON corrupt' into the same 0,0,0,0,0 result — a corrupt cursor silently triggers full replay from event zero instead of surfacing an error.",
      "core/intercore/cmd/ic/events.go:712-733", "P3",
      "single error path for both conditions at :712-733",
      2, 1, 2, 0, None, "event-delivery-at-most-once", ["f-072"], [], None, "upheld"),
    f("f-118", KC,
      "sinceInterspect is loaded and saved but never advanced and never used in any query — a dead cursor slot carried in the persisted payload, documenting that the 5-tuple cursor shape was designed for sources that never joined the UNION.",
      "core/intercore/cmd/ic/events.go:116,143-154,159", "P3",
      "load/save at :116,:159; no query references it",
      2, 1, 1, 0, None, "event-cursor-shape-undocumented", [], [], None, "upheld"),
    f("f-119", KC,
      "DESIGN (proposal, not defect): minimal durable-consumer contract — read-only tail with --auto-advance legacy flag, new `ic events cursor set` ack verb (~40 lines on existing state store, no schema migration), --since-*/--consumer guard, TTL reconciliation, `ic events prune --older-than [--dry-run]` with durable-cursor floor, contracts/events/delivery.md, and consumer-side unique dedup index + INSERT OR IGNORE; sequenced AFTER the f-039/f-040 nil-recorder wiring (delivery of a stream with holes would falsely certify completeness).",
      "core/intercore/cmd/ic/events.go + contracts/events/delivery.md + interverse/interspect/hooks/lib-interspect.sh", "P2",
      "verdict.md command-surface + migration plan; two-release behavioral migration (N: auto-advance default-on deprecated; N+1: read-only default)",
      2, 1, 1, 0, None, "events-delivery-contract-design", ["f-039", "f-040", "f-018", "f-073"], [], None, "raw"),
    # ---- probe-3: FUSE fd-canonization-safety ----
    f("f-120", CS,
      "The lib-intercore.sh twin guard is DOUBLE-BLIND: both copies stamp INTERCORE_WRAPPER_VERSION 1.1.0 over 266 diff lines; the only sync check points at ../../hub/clavain/hooks/lib-intercore.sh — dead since the hub/clavain->os/Clavain move — and even if repointed compares only the identical version string. All 9 runtime hooks execute the Clavain copy while the core copy is the nominal 'source' (executed/edited inverted), and the twins diverge in OPPOSITE directions per function (sentinels fail open in Clavain, temp-file fallback in core; state ops propagate errors in Clavain, swallow in core) — wholesale canonizing either copy flips failure direction for one function class across all 9 hooks (V2: genuine-emergent, upheld).",
      "core/intercore/test-integration.sh:1383 + core/intercore/lib-intercore.sh:9 + os/Clavain/hooks/lib-intercore.sh:9", "P1",
      "guard path nonexistent since repo move; version-only compare; consumer census: 9 hooks source Clavain copy, only test-integration.sh:125,908 executes core copy",
      3, 3, 2, 0, None, "twin-guard-double-blind", ["f-001", "f-025", "f-078"], [],
      "Consolidation alone picks the repo-local 'source' (core) as canonical — the wrong one; contract analysis alone finds each call site internally consistent; only the intersection reveals the executed contract and archived template diverged in opposite directions per function, so neither copy can be canonized wholesale, and the guard that should pin this observes nothing.",
      "upheld"),
    f("f-121", CS,
      "The gitleaks marker string serves two contracts at once — provenance stamp and overwrite-protection key — and the rename migration was declared complete ('[x] 45 .gitleaks.toml files') while 37/46 deployed .gitleaks.toml and 37/47 validators still carry '# demarch-managed' (md5 census: 37x33b2901b demarch vs 10x882585e0 sylveste; marker line is the only delta). Naive grep-both-markers re-attachment would stomp intentional pins; the safe mechanism neither parent finds alone is a historical-template-hash allowlist (re-attach iff deployed hash matches any published template version) plus a v1->v2 migration stamp.",
      "scripts/sync-secret-scan-baseline.sh:55,82-99 + docs/plans/2026-03-26-sylveste-migration-plan.md:39", "P2",
      "md5 census 37/47 demarch-marked; is_managed_file greps only new marker; plan checkbox false for 37",
      1, 2, 3, 0, None, "gitleaks-validator-fleet", ["f-086", "f-002"], [],
      "Contract analysis alone rates the SKIP branch 'protection working as specified'; consolidation alone says 'just add the old marker to the grep' — which destroys the protection semantics; only the intersection exposes that the naive consolidation stomps deliberate pins while the naive contract reading preserves a fleet split the migration plan falsely claims is closed.",
      "raw"),
    f("f-122", CS,
      "SKILL-compact.md is the executed contract while SKILL.md is the edited source: the compact directive (in 10 Clavain SKILL.md files) instructs agents to load the compact unconditionally; 13/15 pairs have SKILL.md newer (up to 126 days), the hash guard confirms 10 stale compacts, 6 pairs lack manifests entirely. The root guard's registry is stale AND contradicts a canonization decision: it tests interflux/flux-drive whose compact was DELIBERATELY deleted in the B4 canonization (sylveste-s46z — compact had silently dropped Phase 2.5 orchestration), plus phantom entries interserve/brainstorming — the consolidation guard demands re-creation of a file consolidation deliberately killed.",
      "scripts/test-compact-freshness.sh:21-36 + os/Clavain/skills/*/SKILL.md compact directives", "P2",
      "13/15 pairs drifted; 'Source hashes differ from manifest' x10; KNOWN_SKILLS includes deleted flux-drive compact + 2 phantoms",
      2, 2, 2, 0, None, "compact-drift-guard-missing", ["f-007", "f-008", "f-089"], ["f-008"],
      "Consolidation alone classifies the compact as a derived artifact ('just regenerate') and misses that regeneration codifies current SKILL.md into the copy agents execute with no fidelity check; contract analysis alone finds the load path working; only the intersection catches that the ecosystem already paid for proof this pair pattern drops orchestration semantics (B4), resolved it by single-sourcing — and the fleet-wide guard still demands the deleted file's re-creation. Partly contradicts f-008's 'no guard exists for Clavain pairs': a root guard exists but its registry is broken.",
      "raw"),
    f("f-123", CS,
      "The ~60 drifted doctrine blocks are cited by no gate as TEXT, but PHILOSOPHY.md/AGENTS.md content is a hash input to session-freshness-gate.sh's orientation manifest whose exit code IS a behavior contract (0=skip, 1=full orientation; .claude/session-state.json holds the live hash) — a doctrine-canonization sweep flips every wired repo's gate to 'stale', forcing mass re-orientation sessions indistinguishable from real drift; the sweep must be staged or paired with a session-state manifest reset. Backfill TARGETS registry also stale (interserve phantom; os/clavain lowercase breaks on case-sensitive zklw) (V3: mechanism upheld).",
      "scripts/session-freshness-gate.sh:50 + scripts/backfill-philosophy-protocol.py:15-46", "P3",
      "ORIENTATION_FILES at :50; live hash in .claude/session-state.json:7; only non-doc doctrine reference is a transcript artifact",
      2, 1, 2, 0, None, "doctrine-hash-gate-coupling", ["f-003", "f-092"], [],
      "Consolidation alone sees inert doctrine text and schedules a harmless merge sweep; contract analysis alone checks 'does any gate parse this text?' — answer no — and also clears it; only the intersection catches that the file's content HASH, not its text, is the load-bearing input, so canonizing 'informational' doctrine changes a behavioral signal across ~60 repos at once.",
      "upheld"),
    f("f-124", CS,
      "Three registries answer 'what is the fleet' and install machinery reads different ones per host: marketplace.json (66 hand-listed; 8 on-disk dirs unlisted; interjawn listed but absent from disk -> 404), profile-pack overrides embedded in the inventory generator (28/71 dirs unlisted, keyword-heuristic classification), and Kimi/Gemini generators that bypass both and discover the filesystem — so Kimi/Gemini users can install plugins Claude Code users cannot see, and Claude Code offers a phantom. No declared canonical fleet definition; check-rig-drift.sh validates inventory<->marketplace<->rig but not marketplace<->disk.",
      "core/marketplace/.claude-plugin/marketplace.json + scripts/interverse_inventory.py:38-97,499-511 + gen-kimi-manifests.py:339-346", "P3",
      "8 unlisted dirs enumerated; interjawn phantom; keyword heuristic at :499-511",
      1, 2, 2, 0, None, "routing-ghosts-cold-spots", ["f-033", "f-089"], [],
      "Consolidation alone sees three overlapping lists and says 'pick one'; contract analysis alone traces each consumer to its own list and finds each path self-consistent; only the intersection reveals that choosing a registry is a semantic decision about which host's install surface is authoritative — and the existing drift guard never checks the registry against the disk.",
      "raw"),
    f("f-125", CS,
      "Version-stamp schizophrenia in the twin library: header comment says 'Version: 0.1.0 (source: infra/intercore/lib-intercore.sh)' — a provenance path that no longer exists — while the machine stamp says 1.1.0, historical docs cite v0.4.0/v0.6.0, AGENTS.md claims '44 functions' and cli-reference.md '45 functions' against twin surfaces that actually differ (Clavain copy adds 5 run_* wrappers) — three version witnesses plus two surface-size witnesses, so no consumer can tell which string IS the contract version, and any canonization that bumps only one witness re-creates the ambiguity that hid the 1.1.0/266-diff-lines split.",
      "core/intercore/lib-intercore.sh:2,9 + core/intercore/AGENTS.md:37 + agents/cli-reference.md:10", "P3",
      "three version strings + two function counts verified at cited lines",
      1, 1, 2, -1, "smell", "stamp-trusted-content-drift", ["f-001", "f-087", "f-078"], [],
      "Consolidation alone sees stale comments to tidy; contract analysis alone checks the machine-readable stamp, fine in isolation at each site; only the intersection catches the competing witnesses — the ambiguity is the defect, not any single stale string.",
      "raw"),
]

lines = [json.loads(l) for l in LEDGER.read_text().splitlines() if l.strip()]
by_id = {d["id"]: d for d in lines}
for fid, refs in BACK_CONV.items():
    d = by_id[fid]
    for r in refs:
        if r not in d["convergence_refs"]:
            d["convergence_refs"].append(r)
for fid, refs in BACK_DIS.items():
    d = by_id[fid]
    for r in refs:
        if r not in d["disagreement_refs"]:
            d["disagreement_refs"].append(r)

ids = [n["id"] for n in NEW]
assert len(ids) == len(set(ids)) == 33, ids
assert ids[0] == "f-093" and ids[-1] == "f-125"
for n in NEW:
    assert n["id"] not in by_id
    for r in n["convergence_refs"] + n["disagreement_refs"]:
        assert r in by_id or r in ids, (n["id"], r)

# single rewrite: existing lines with back-ref stamps + appended round-2 findings
LEDGER.write_text("".join(json.dumps(d, ensure_ascii=False) + "\n" for d in lines + NEW))
print(f"ledger now {len(lines) + len(NEW)} lines; back-stamped {len(BACK_CONV)} conv + {len(BACK_DIS)} dis targets")
